from app.core.celery_app import celery_app
from .challenge_result_task import challenge_result_task
from .daily_quests_task import daily_quests_task
from .notification_dispatch_task import notification_dispatch_task
from .reward_distribution_task import reward_distribution_task
from .world_events_task import world_events_task
