"""
Enhanced RPG Life Database Models

This module adds support for:
- Single active goal system with auto-quest matching
- Quest verification mechanisms (photo, geolocation, questions)
- Health decay and armor system
- Step tracker integration
- Extended skill descriptions
"""

from datetime import datetime

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    JSON,
    UniqueConstraint,
)
from sqlalchemy.orm import relationship

from app.core.dates import utc_now
from app.core.database import Base


class UserGoal(Base):
    """
    Represents a user's goal. Only ONE active goal can exist at a time.
    This replaces the old multi-goal system with a focused single-goal approach.
    """
    __tablename__ = "user_goals"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    
    # Goal identification
    goal_type = Column(String, nullable=False, index=True)  # self_development, weight_loss, etc.
    title = Column(String, nullable=False)
    description = Column(Text)
    
    # Goal duration and progress
    duration_days = Column(Integer, nullable=False)
    started_at = Column(DateTime, default=utc_now)
    deadline_at = Column(DateTime, nullable=False)
    required_quest_points = Column(Integer, nullable=False)
    current_quest_points = Column(Integer, default=0)
    
    # Visual properties
    icon = Column(String, default="🎯")
    accent_color = Column(String, default="#4CAF50")
    
    # Status - only ONE goal can be active at a time
    status = Column(String, default="active", index=True)  # active, completed, abandoned, expired
    
    # AI-generated goal-specific details
    ai_generated_quests = Column(JSON, nullable=True)  # Custom quests generated by AI for this goal
    focus_areas = Column(JSON, nullable=True)  # Areas AI should focus on when generating quests
    
    # Timestamps
    completed_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=utc_now)
    updated_at = Column(DateTime, default=utc_now, onupdate=utc_now)

    user = relationship("User", back_populates="user_goals")


class QuestVerification(Base):
    """
    Stores verification data for quest completion.
    Supports multiple verification methods:
    - photo: Photo with timestamp
    - location: GPS coordinates
    - question: Verification questions
    """
    __tablename__ = "quest_verifications"

    id = Column(Integer, primary_key=True, index=True)
    quest_id = Column(Integer, ForeignKey("quests.id"), nullable=False, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    
    # Verification type and data
    verification_type = Column(String, nullable=False)  # photo, location, question, manual
    verification_data = Column(JSON, nullable=True)  # Stores the actual verification info
    
    # Photo verification
    photo_url = Column(String, nullable=True)
    photo_timestamp = Column(DateTime, nullable=True)
    photo_metadata = Column(JSON, nullable=True)  # EXIF data, location in photo, etc.
    
    # Location verification
    latitude = Column(Float, nullable=True)
    longitude = Column(Float, nullable=True)
    location_accuracy = Column(Float, nullable=True)
    location_name = Column(String, nullable=True)
    location_timestamp = Column(DateTime, nullable=True)
    
    # Question verification
    questions_answers = Column(JSON, nullable=True)  # Questions and user answers
    verification_question = Column(String, nullable=True)
    verification_answer = Column(String, nullable=True)
    
    # Verification status
    is_verified = Column(Boolean, default=False)
    verified_at = Column(DateTime, nullable=True)
    verified_by = Column(String, nullable=True)  # system, ai, manual
    
    # Notes
    notes = Column(Text, nullable=True)
    created_at = Column(DateTime, default=utc_now)

    quest = relationship("Quest", back_populates="verification")


class Quest(Base):
    """Enhanced Quest model with verification support and goal linking"""
    __tablename__ = "quests"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), index=True)
    class_progress_id = Column(Integer, ForeignKey("user_class_progress.id"), nullable=True, index=True)
    
    # Goal association - links quest to a specific goal
    goal_id = Column(Integer, ForeignKey("user_goals.id"), nullable=True, index=True)
    
    title = Column(String)
    description = Column(Text)
    xp_reward = Column(Integer)
    crystal_reward = Column(Integer)
    rarity = Column(String, default="common")
    goal_type = Column(String, nullable=True)
    
    # Quest origin tracking
    is_custom = Column(Boolean, default=False)
    is_ai_generated = Column(Boolean, default=False)
    ai_prompt = Column(Text, nullable=True)  # The prompt used to generate this quest
    
    # Quest matching data
    difficulty = Column(String, default="medium")  # easy, medium, hard, epic
    category = Column(String, nullable=True)  # Links to goal category
    tags = Column(JSON, nullable=True)  # Additional tags for matching
    
    # Verification requirements
    requires_verification = Column(Boolean, default=False)
    verification_type = Column(String, nullable=True)  # photo, location, question, any
    required_photos = Column(Integer, default=0)
    required_location = Column(Boolean, default=False)
    verification_questions = Column(JSON, nullable=True)  # List of verification questions
    
    # Completion tracking
    is_completed = Column(Boolean, default=False, index=True)
    completed_at = Column(DateTime, nullable=True, index=True)
    verified_at = Column(DateTime, nullable=True)
    
    # Quest type and objectives
    quest_type = Column(String, default="daily", index=True)
    objective_type = Column(String, nullable=True)
    target_value = Column(Integer, nullable=True)
    current_value = Column(Integer, default=0)
    
    # Expiration
    expires_at = Column(DateTime, nullable=True, index=True)
    
    # Challenge linkage
    challenge_id = Column(Integer, ForeignKey("challenges.id"), nullable=True, index=True)
    
    created_at = Column(DateTime, default=utc_now, index=True)
    icon = Column(String, default="📝")

    user = relationship("User", back_populates="quests")
    class_prog = relationship("UserClassProgress", back_populates="quests")
    challenge = relationship("Challenge", back_populates="boss_quests")
    verification = relationship("QuestVerification", back_populates="quest", uselist=False)
    goal = relationship("UserGoal", back_populates="quests")


class UserGoalQuest(Base):
    """Links quests to goals for tracking which quests contribute to which goal"""
    __tablename__ = "goal_quests"

    id = Column(Integer, primary_key=True, index=True)
    goal_id = Column(Integer, ForeignKey("user_goals.id"), nullable=False, index=True)
    quest_id = Column(Integer, ForeignKey("quests.id"), nullable=False, index=True)
    
    quest_points = Column(Integer, default=1)  # How many points this quest gives to the goal
    contributed_at = Column(DateTime, default=utc_now)

    goal = relationship("UserGoal", back_populates="goal_quests")
    quest = relationship("Quest", back_populates="goal_links")


class User(Base):
    """Enhanced User model with health and armor system"""
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True)
    hashed_password = Column(String)
    name = Column(String, nullable=True)
    birth_year = Column(Integer, nullable=True)
    gender = Column(String, default="unspecified")
    language_preference = Column(String, default="ru")
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=utc_now)
    
    # Health System
    max_health = Column(Integer, default=100)
    current_health = Column(Integer, default=100)
    armor_value = Column(Integer, default=0)
    
    # Last activity tracking for health decay
    last_active_at = Column(DateTime, default=utc_now)
    last_health_update = Column(DateTime, default=utc_now)
    
    # Step tracker integration
    total_steps = Column(Integer, default=0)
    daily_step_goal = Column(Integer, default=10000)
    last_step_sync = Column(DateTime, nullable=True)
    
    # Incomplete quests penalty tracking
    missed_quests_count = Column(Integer, default=0)
    consecutive_missed_days = Column(Integer, default=0)

    class_progress = relationship("UserClassProgress", back_populates="user", cascade="all, delete-orphan")
    quests = relationship("Quest", back_populates="user", cascade="all, delete-orphan")
    completed_quests = relationship("CompletedQuest", back_populates="user", cascade="all, delete-orphan")
    user_achievements = relationship("UserAchievement", back_populates="user", cascade="all, delete-orphan")
    inventory_items = relationship("UserInventory", back_populates="user", cascade="all, delete-orphan")
    equipment = relationship("CharacterEquipment", back_populates="user", cascade="all, delete-orphan")
    steps_records = relationship("DailySteps", back_populates="user", cascade="all, delete-orphan")
    calories_records = relationship("DailyCalories", back_populates="user", cascade="all, delete-orphan")
    water_records = relationship("DailyWater", back_populates="user", cascade="all, delete-orphan")
    user_goals = relationship("UserGoal", back_populates="user", cascade="all, delete-orphan")
    created_challenges = relationship("Challenge", foreign_keys="Challenge.creator_id", back_populates="creator")
    received_challenges = relationship("Challenge", foreign_keys="Challenge.opponent_id", back_populates="opponent")
    won_challenges = relationship("Challenge", foreign_keys="Challenge.winner_id", back_populates="winner")
    challenge_entries = relationship("ChallengeParticipant", back_populates="user", cascade="all, delete-orphan")
    sent_friend_requests = relationship(
        "FriendRequest",
        foreign_keys="FriendRequest.requester_id",
        back_populates="requester",
        cascade="all, delete-orphan",
    )
    received_friend_requests = relationship(
        "FriendRequest",
        foreign_keys="FriendRequest.receiver_id",
        back_populates="receiver",
        cascade="all, delete-orphan",
    )
    friendships = relationship(
        "Friendship",
        foreign_keys="Friendship.user_id",
        back_populates="user",
        cascade="all, delete-orphan",
    )
    coop_entries = relationship("CoopQuestParticipant", back_populates="user", cascade="all, delete-orphan")
    sent_challenge_invitations = relationship(
        "ChallengeInvitation",
        foreign_keys="ChallengeInvitation.sender_id",
        back_populates="sender",
        cascade="all, delete-orphan",
    )
    received_challenge_invitations = relationship(
        "ChallengeInvitation",
        foreign_keys="ChallengeInvitation.receiver_id",
        back_populates="receiver",
        cascade="all, delete-orphan",
    )
    push_devices = relationship("PushDevice", back_populates="user", cascade="all, delete-orphan")
    social_accounts = relationship("UserSocialAccount", back_populates="user", cascade="all, delete-orphan")
    notification_events = relationship(
        "NotificationEvent",
        foreign_keys="NotificationEvent.user_id",
        back_populates="user",
        cascade="all, delete-orphan",
    )


class UserClassProgress(Base):
    """Enhanced class progress with extended skill descriptions"""
    __tablename__ = "user_class_progress"
    __table_args__ = (UniqueConstraint("user_id", "class_name", name="uq_user_class_progress_user_class"),)

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    class_name = Column(String, nullable=False, index=True)
    display_name = Column(String, nullable=True)
    strength = Column(Float, default=1.0)
    agility = Column(Float, default=1.0)
    intellect = Column(Float, default=1.0)
    level = Column(Integer, default=1)
    current_xp = Column(Integer, default=0)
    crystals = Column(Integer, default=0)
    streak = Column(Integer, default=0)
    last_activity = Column(DateTime, default=utc_now)
    last_bonus = Column(DateTime, nullable=True)
    is_unlocked = Column(Boolean, default=False, index=True)
    
    # Extended skill properties
    skill_descriptions_unlocked = Column(JSON, default=dict)  # Maps skill_id to detailed description
    
    user = relationship("User", back_populates="class_progress")
    equipment = relationship("CharacterEquipment", back_populates="class_progress", uselist=False)
    quests = relationship("Quest", back_populates="class_prog")
    steps_records = relationship("DailySteps", back_populates="class_prog")
    calories_records = relationship("DailyCalories", back_populates="class_prog")
    water_records = relationship("DailyWater", back_populates="class_prog")


class CompletedQuest(Base):
    __tablename__ = "completed_quests"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), index=True)
    quest_id = Column(Integer, ForeignKey("quests.id"), index=True)
    completed_at = Column(DateTime, default=utc_now, index=True)
    xp_earned = Column(Integer)
    crystals_earned = Column(Integer)
    
    # Verification info for completed quests
    was_verified = Column(Boolean, default=False)
    verification_method = Column(String, nullable=True)

    user = relationship("User", back_populates="completed_quests")


class DailySteps(Base):
    __tablename__ = "daily_steps"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), index=True)
    class_progress_id = Column(Integer, ForeignKey("user_class_progress.id"), nullable=True, index=True)
    steps = Column(Integer, default=0)
    target_steps = Column(Integer, default=10000)
    date = Column(DateTime, default=utc_now, index=True)
    synced_at = Column(DateTime, nullable=True)
    xp_earned = Column(Integer, default=0)
    crystals_earned = Column(Integer, default=0)
    is_reward_claimed = Column(Boolean, default=False)
    
    # Step source tracking
    source = Column(String, default="manual")  # manual, healthkit, googlefit, etc.

    user = relationship("User", back_populates="steps_records")
    class_prog = relationship("UserClassProgress", back_populates="steps_records")


class DailyCalories(Base):
    __tablename__ = "daily_calories"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), index=True)
    class_progress_id = Column(Integer, ForeignKey("user_class_progress.id"), nullable=True, index=True)
    calories_consumed = Column(Integer, default=0)
    calories_burned = Column(Integer, default=0)
    net_calories = Column(Integer, default=0)
    target_calories = Column(Integer, default=2000)
    date = Column(DateTime, default=utc_now, index=True)

    user = relationship("User", back_populates="calories_records")
    class_prog = relationship("UserClassProgress", back_populates="calories_records")


class DailyWater(Base):
    __tablename__ = "daily_water"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), index=True)
    class_progress_id = Column(Integer, ForeignKey("user_class_progress.id"), nullable=True, index=True)
    glasses = Column(Integer, default=0)
    target_glasses = Column(Integer, default=8)
    ml = Column(Integer, default=0)
    date = Column(DateTime, default=utc_now, index=True)
    last_updated = Column(DateTime, default=utc_now, onupdate=utc_now)

    user = relationship("User", back_populates="water_records")
    class_prog = relationship("UserClassProgress", back_populates="water_records")


class HealthAchievements(Base):
    __tablename__ = "health_achievements"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), index=True)
    steps_total = Column(Integer, default=0)
    steps_days_10k = Column(Integer, default=0)
    steps_streak = Column(Integer, default=0)
    calories_total = Column(Integer, default=0)
    calories_days_target = Column(Integer, default=0)
    water_total_glasses = Column(Integer, default=0)
    water_streak = Column(Integer, default=0)

    user = relationship("User", backref="health_achievements")


class Achievement(Base):
    __tablename__ = "achievements"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, unique=True)
    description = Column(String)
    icon = Column(String, default="🏆")
    xp_reward = Column(Integer, default=0)
    crystal_reward = Column(Integer, default=0)

    users = relationship("UserAchievement", back_populates="achievement")


class UserAchievement(Base):
    __tablename__ = "user_achievements"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), index=True)
    achievement_id = Column(Integer, ForeignKey("achievements.id"), index=True)
    earned_at = Column(DateTime, default=utc_now)

    user = relationship("User", back_populates="user_achievements")
    achievement = relationship("Achievement", back_populates="users")


class DailyBonus(Base):
    __tablename__ = "daily_bonuses"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), index=True)
    day_number = Column(Integer)
    bonus_xp = Column(Integer)
    bonus_crystals = Column(Integer)
    claimed_at = Column(DateTime, default=utc_now, index=True)

    user = relationship("User")


class Challenge(Base):
    __tablename__ = "challenges"

    id = Column(Integer, primary_key=True, index=True)
    creator_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    opponent_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    title = Column(String, nullable=False)
    description = Column(Text, default="")
    challenge_type = Column(String, default="duel", index=True)
    objective_type = Column(String, nullable=False)
    target_value = Column(Integer, default=0)
    reward_xp = Column(Integer, default=0)
    reward_crystals = Column(Integer, default=0)
    reward_chest = Column(Boolean, default=False)
    status = Column(String, default="active", index=True)
    start_at = Column(DateTime, default=utc_now)
    end_at = Column(DateTime, nullable=False, index=True)
    winner_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    created_at = Column(DateTime, default=utc_now, index=True)
    accepted_at = Column(DateTime, nullable=True)
    responded_at = Column(DateTime, nullable=True)
    resolved_at = Column(DateTime, nullable=True)

    creator = relationship("User", foreign_keys=[creator_id], back_populates="created_challenges")
    opponent = relationship("User", foreign_keys=[opponent_id], back_populates="received_challenges")
    winner = relationship("User", foreign_keys=[winner_id], back_populates="won_challenges")
    participants = relationship("ChallengeParticipant", back_populates="challenge", cascade="all, delete-orphan")
    boss_quests = relationship("Quest", back_populates="challenge")


class ChallengeParticipant(Base):
    __tablename__ = "challenge_participants"

    id = Column(Integer, primary_key=True, index=True)
    challenge_id = Column(Integer, ForeignKey("challenges.id"), nullable=False, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    result_value = Column(Integer, default=0)
    joined_at = Column(DateTime, default=utc_now)
    is_creator = Column(Boolean, default=False)

    challenge = relationship("Challenge", back_populates="participants")
    user = relationship("User", back_populates="challenge_entries")
