[pytest]
testpaths = tests
pythonpath = .
addopts = -p no:cacheprovider
filterwarnings =
    ignore:'asyncio\.iscoroutinefunction' is deprecated and slated for removal in Python 3\.16; use inspect\.iscoroutinefunction\(\) instead:DeprecationWarning:fastapi\.routing
    ignore:'asyncio\.iscoroutinefunction' is deprecated and slated for removal in Python 3\.16; use inspect\.iscoroutinefunction\(\) instead:DeprecationWarning:starlette\._utils
    ignore:datetime\.datetime\.utcnow\(\) is deprecated:DeprecationWarning:jose\.jwt
